### ISSUE TITLE
Error creating berkeley DB running initial.sh

### ISSUE THREAD

**Issue by noahkw** [evanc577/sourcecatcher#8]
Hi,

I am trying to add Docker support and keep running into the following error executing initial.sh:

```
Traceback (most recent call last):
  File "/app/feature_match.py", line 188, in <module>
    gen_cbir()
  File "/app/feature_match.py", line 88, in gen_cbir
    descriptors.open("working/descriptors.bdb")
bsddb3.db.DBNoSuchFileError: (2, 'No such file or directory')
```

I've tried to create the file with touch and to change the path to an absolute one, to no avail. Scraping the pics and the creation of the SQLite DB seem to be working fine.

**Comment by evanc577** [comment]
There were some issues with initial setup that should be fixed now on the master branch. You also might want to recreate the virtualenv and reinstall the requirements, I pinned some module versions that broke functionality when updated.

Sorry for the late response, I didn't have notifications set up on this repo.

**Comment by noahkw** [comment]
Thanks a lot, that seems to have worked, although the scipy build still seems all sorts of messed up. I had to first install all the other packages.
